# Generated by Django 3.2.16 on 2023-01-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
